version: "3.4"
services:
  hydradx-node.public.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: master
    volumes:
    - "hydra_dx:/root/.local/share/hydra-dx"
    environment:
      - "EXTRA_OPTS=--chain=lerna"
    image: "hydradx-node.public.dappnode.eth:0.1.1"
    ports:
      - "30303"
      - 30303/udp
    restart: unless-stopped
volumes:
  hydra_dx: {}
